### ISSUE TITLE
定时重启报错

### ISSUE THREAD

**Issue by MoonofBridge24** [ENIACJushi/AutoRestart#1]
定时重启功能和等待玩家全部退出后重启的功能都报错，不能正常使用

**Comment by ENIACJushi** [comment]
等待玩家全部退出后重启的设计确实存在漏洞，已修复；
定时重启报错了个啥，可以复制一下看看吗

**Comment by MoonofBridge24** [comment]
报错倒是没有，但是到达设定时间后仅关闭服务器，并没有正常重启，其次是每次开服貌似并没有自动导入重启任务，必须手动reload才会生效

**Comment by ENIACJushi** [comment]
已修复，不再受服务器tps影响
